Repository angular/angular.js, pull requests merged in 2018-10, with the labels that each got.

#16709 fix(ngStyle): skip setting empty value when new style has the property
  src/ng/directive/ngStyle.js
  test/ng/directive/ngStyleSpec.js
Labels: cla: yes, component: misc core, needs: test, type: bug

#16714 chore(*): update minimum Yarn version, do some Yarn-related cleanups
  .travis.yml
  Gruntfile.js
  package.json
  scripts/jenkins/build.sh
  scripts/jenkins/init-node.sh
  scripts/jenkins/release.sh
  scripts/travis/before_build.sh
  scripts/travis/build.sh
  yarn.lock
Labels: cla: yes

#16730 chore(*): update Sauce Connect from 4.4.12 to 4.5.1
  lib/saucelabs/start_tunnel.sh
Labels: cla: yes

#16713 fix(ngMock): make matchLatestDefinitionEnabled work
  src/ngMock/angular-mocks.js
Labels: cla: yes, component: ngMock, needs: review, severity: broken expected use

#16712 chore: properly isolate module tests
  Gruntfile.js
  angularFiles.js
  karma-modules.conf.js
  lib/grunt/plugins.js
  src/ngMessageFormat/messageFormatService.js
  test/ngCookies/cookieWriterSpec.js
  test/ngMock/angular-mocksSpec.js
  test/ngResource/resourceSpec.js
Labels: cla: yes, needs: review, type: chore

#16715 fix(urlUtils): make IPv6 URL's hostname wrapped in square brackets in IE/Edge
  src/ng/urlUtils.js
  test/ng/urlUtilsSpec.js
Labels: browser: Edge, browser: IE10, browser: IE11, browser: IE9, cla: yes, component: $location, severity: broken expected use
