Repository angular/angular.js, pull requests merged in 2018-02, with the labels that each got.

#16457 chore(docs.angularjs.org): allow robots in partials/ but prevent inde…
  docs/app/assets/robots.txt
  scripts/docs.angularjs.org-firebase/firebase.json
Labels: cla: yes

#16456 docs(*): Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: cla: yes, type: docs

#16460 docs(misc): add version-support-status page
  README.md
  docs/app/assets/css/docs.css
  docs/content/api/index.ngdoc
  docs/content/misc/version-support-status.ngdoc
Labels: cla: yes, needs: review, type: docs

#16473 docs(README): fix incorrect version-support-status
  README.md
Labels: cla: yes
