Repository angular/angular.js, pull requests merged in 2018-08, with the labels that each got.

#16614 feat($compile): add support for arbitrary property and event bindings
  docs/content/error/$compile/ctxoverride.ngdoc
  docs/content/error/$compile/nodomevents.ngdoc
  src/.eslintrc.json
  src/ng/compile.js
  src/ng/directive/ngEventDirs.js
  test/ng/compileSpec.js
  test/ng/ngOnSpec.js
  test/ng/ngPropSpec.js
Labels: cla: yes, component: $compile, frequency: moderate, severity: inconvenient, type: feature

#16627 docs(ngProp, ngOn)
  src/ng/compile.js
  src/ng/sce.js
Labels: cla: yes, needs: review, type: docs

#16656 fix(select): allow to select first option with value `undefined`
  src/ng/directive/select.js
  test/ng/directive/selectSpec.js
Labels: cla: yes, component: forms, needs: review, type: bug

#16652 fix(ngHref): allow numbers as input
  src/ng/sce.js
  test/ng/directive/ngHrefSpec.js
Labels: cla: yes, component: $compile, component: misc core, severity: regression
