Repository angular/angular.js, pull requests merged in 2018-04, with the labels that each got.

#16518 fix(jqLite): use XHTML-compliant HTML as input for jqLite
  src/Angular.js
  src/ng/compile.js
Labels: cla: yes, component: jqLite, type: bug

#16517 docs(jqLite): document append doesn't work well with a multi-node object
  src/jqLite.js
Labels: cla: yes, component: jqLite, type: docs

#16494 test($rootScope): add tests clarifying $watchGroup oldValues behavior
  test/ng/rootScopeSpec.js
Labels: cla: yes

#16477 test($parse): add tests for watching one-time array/object literals
  test/ng/parseSpec.js
Labels: cla: yes

#16512 fix(jqLite): make removeData() not remove event handlers
  src/Angular.js
  src/jqLite.js
  test/jqLiteSpec.js
Labels: cla: yes, component: jqLite, needs: breaking change

#16390 fix(input): Take timezone into account when validating minimum and ma…
  src/ng/directive/input.js
  test/ng/directive/inputSpec.js
Labels: cla: no, component: forms, type: bug

#16336 fix(input): allow overriding timezone for date input types
  src/.eslintrc.json
  src/Angular.js
  src/ng/directive/input.js
  src/ng/directive/ngModelOptions.js
  test/ng/directive/inputSpec.js
Labels: cla: yes, component: forms, frequency: moderate, severity: broken expected use, type: bug

#16526 test(input): fix date type tests with max + timezone
  test/ng/directive/inputSpec.js
Labels: cla: yes

#15890 chore(*): remove manualLowercase & manualUppercase functions
  src/.eslintrc.json
  src/Angular.js
  test/.eslintrc.json
  test/AngularSpec.js
Labels: cla: yes
