Repository angular/angular.js, pull requests merged in 2018-07, with the labels that each got.

#16622 docs(changelog, guide/Migration): add info about $sce BC in 1.7
  CHANGELOG.md
  docs/content/guide/migration.ngdoc
Labels: cla: yes, needs: review, type: docs

#16618 refactor($location): move repeated path normalization code into helper method
  src/ng/location.js
Labels: cla: yes, component: $location, type: refactor

#16629 fix(ngEventDirs): check for $rootScope.$$phase in event handler and don't $apply if already in $digest
  src/ng/directive/ngEventDirs.js
  test/ng/directive/ngEventDirsSpec.js
Labels: cla: no

#16645 fix(Angular): add workaround for Safari / Webdriver error
  src/Angular.js
Labels: cla: yes

#16647 fix($compile): use correct parent element when requiring on html element
  src/ng/compile.js
  test/e2e/fixtures/directive-require-html/index.html
  test/e2e/fixtures/directive-require-html/script.js
  test/e2e/tests/directive-require-html.spec.js
Labels: cla: yes, component: forms, frequency: low, needs: review, severity: broken expected use, type: bug
