Repository angular/angular.js, pull requests merged in 2018-06, with the labels that each got.

#16590 https link to editorconfig.org
  .editorconfig
Labels: cla: yes

#16511 Feat: ngRef directive to publish controllers, or elements into current scope
  angularFiles.js
  docs/content/error/ngRef/noctrl.ngdoc
  docs/content/error/ngRef/nonassign.ngdoc
  src/AngularPublic.js
  src/ng/directive/ngRef.js
  test/helpers/matchers.js
  test/ng/directive/ngRefSpec.js
Labels: cla: yes, component: misc core, needs: review, type: feature

#16591 feat(errorHandlingConfig): add option to exclude error params from url
  src/minErr.js
  test/minErrSpec.js
Labels: cla: no, component: misc core, frequency: high, needs: review, severity: inconvenient, type: feature

#16587 feat(ngMessages): add support for default message
  src/ngMessages/messages.js
  test/ngMessages/messagesSpec.js
Labels: cla: no, component: ngMessages, frequency: moderate, needs: review, severity: inconvenient, type: feature

#16584 Feat input timeformat
  src/ng/directive/input.js
  src/ng/directive/ngModelOptions.js
  test/ng/directive/inputSpec.js
Labels: cla: yes, component: forms, frequency: high, needs: review, severity: confusing, type: feature

#16601 feat(form.FormController): add $getControls()
  src/ng/directive/form.js
  test/ng/directive/formSpec.js
Labels: cla: yes, component: forms, frequency: moderate, needs: review, severity: inconvenient, type: feature

#16610 chore(docs-app): ensure ToC links contain the path
  docs/app/src/directives.js
Labels: cla: yes, frequency: moderate, needs: review, severity: inconvenient, type: chore, type: docs, type: infrastructure
