Repository angular/angular.js, pull requests merged in 2018-03, with the labels that each got.

#16465 fix($cookies): remove the deprecated $cookieStore factory
  angularFiles.js
  docs/content/api/index.ngdoc
  src/ngCookies/cookieStore.js
  test/ngCookies/cookieStoreSpec.js
Labels: cla: yes, component: ngCookies, needs: breaking change

#16489 docs(ngShow/ngHide): add note about flicker when toggling elements
  src/ng/directive/ngShowHide.js
Labels: cla: yes, component: misc core, component: ngAnimate, type: docs

#16493 chore(travis): update iOs test browsers
  karma-shared.conf.js
  scripts/travis/build.sh
  test/ng/directive/ngOptionsSpec.js
Labels: cla: yes

#16491 minErr: link to actual url and remove url from message params
  src/minErr.js
  test/minErrSpec.js
Labels: cla: yes, component: misc core, type: feature

#16490 docs(guide/Internet Explorer Compatibility): Include warnings for usage of 'disabled' attribute
  docs/content/guide/ie.ngdoc
Labels: cla: no, needs: work

#16515 tests(ngMock): remove a broken jqLite cache clearing
  test/ngMock/angular-mocksSpec.js
Labels: cla: yes

#16516 chore(*): stop testing on Edge 15 due to its instability
  scripts/travis/build.sh
Labels: browser: Edge, cla: yes, type: chore
