Repository angular/angular.js, pull requests merged in 2018-05, with the labels that each got.

#16547 docs(angular.Module): improved documentation for component method
  src/loader.js
Labels: cla: yes

#16548 docs(guide/Components): add link to documentation for component method
  docs/content/guide/component.ngdoc
Labels: cla: yes

#16555 test($sanitize): exclude elclob test in Edge 17
  test/ngSanitize/sanitizeSpec.js
Labels: cla: yes

#16559 test(Angular): remove special case for Edge
  test/AngularSpec.js
Labels: cla: yes

#16554 refactor($compile): remove workaround for chrome bug fixed in v50
  src/ng/compile.js
Labels: cla: yes

#16553 feat($compile): add one-way collection bindings
  src/ng/compile.js
  test/ng/compileSpec.js
Labels: cla: yes, component: $compile, type: feature

#16544 feat(ngCookies): support sameSite option
  src/ngCookies/cookieWriter.js
  src/ngCookies/cookies.js
  test/ngCookies/cookieWriterSpec.js
Labels: cla: yes, component: ngCookies, type: feature

#16573 docs(input[number]): note issue with large number and step validation
  src/ng/directive/input.js
Labels: cla: yes

#16577 docs(ngMockE2E): add docs for $httpBackend.matchLatestDefinitionEnabl…
  src/ngMock/angular-mocks.js
Labels: cla: yes

#15555 fix($compile): support transcluding multi-element directives
  src/ng/compile.js
  test/ng/compileSpec.js
Labels: cla: yes, component: $compile, frequency: low, needs: review, severity: broken expected use, type: bug
